import { describe, expect, it } from 'vitest';
import { readFileSync, readdirSync } from 'node:fs';

import { shotSizes } from '@/ui/Shot';

/*  The sizes `Shot` hands next/image are the sizes the files actually are.
 *
 *  next/image uses width and height to reserve an aspect-ratio box before the
 *  image arrives, and `Shot` used to pass 2880x1800 for every name. Five of the
 *  six are that. `gallery` is 2880x3080 - `dew_shot gallery` sizes itself to
 *  its laid-out content, so its height moves whenever the design system gains
 *  a control - so the design page reserved a 16:10 slot for an image nearly
 *  square and then jumped by most of a screen when it loaded.
 *
 *  The number cannot simply be corrected and left, because the file it
 *  describes is regenerated by hand: `./scripts/gen-shots.sh` is run
 *  deliberately after a UI change worth showing, and .ai/rules/website.md says
 *  in as many words that nothing checks the PNGs byte-wise. So this reads the
 *  header rather than trusting the table.
 */

/** Width and height out of a PNG's IHDR, which is at a fixed offset: an
 *  8-byte signature, a 4-byte length, the 4-byte type, then the two
 *  big-endian dimensions. No decoder needed for two numbers. */
function pngSize(path: string): { width: number; height: number } {
  const bytes = readFileSync(path);

  expect(bytes.subarray(1, 4).toString('ascii'), `${path} is not a PNG`).toBe('PNG');
  expect(bytes.subarray(12, 16).toString('ascii'), `${path} has no IHDR`).toBe('IHDR');

  return { width: bytes.readUInt32BE(16), height: bytes.readUInt32BE(20) };
}

describe('the screenshots', () => {
  const names = Object.keys(shotSizes);

  it('has shots to be a gate over', () => {
    expect(names.length).toBeGreaterThan(4);
  });

  it('is the size the component reserves a box for', () => {
    for (const [name, expected] of Object.entries(shotSizes))
      expect(pngSize(`public/shots/${name}.png`), name).toEqual(expected);
  });

  it('names every file in public/shots and no other', () => {
    // Both directions. A PNG nothing references is dead weight in the export;
    // a name with no PNG is a broken image.
    const onDisk = readdirSync('public/shots')
      .filter((file) => file.endsWith('.png'))
      .map((file) => file.replace(/\.png$/, ''))
      .sort();

    expect(names.sort()).toEqual(onDisk);
  });
});
