// =============================================================================
// src/generated/design-tokens.json -> src/app/theme.generated.css
//
//     node scripts/gen-theme.mjs           write it
//     node scripts/gen-theme.mjs --check   fail if what is committed is stale
//
// Tailwind v4 rather than v3, and this file is the reason. In v4 `@theme`
// both defines the custom property on :root AND generates the utilities, so
// one declaration is one home. A v3 tailwind.config.js would hold the palette
// and anything needing the raw value - a gradient stop, a color-mix - would
// need a second :root block kept in step by hand. That is the second
// vocabulary src/ui/design/Tokens.h exists to end, rebuilt in CSS.
//
// The namespace resets are load-bearing. `--color-*: initial` deletes
// Tailwind's own palette, so `bg-blue-500` and `bg-slate-800` do not exist and
// emit nothing; `--spacing: initial` deletes the dynamic p-3/p-7 scale, leaving
// only the seven rungs dew names. That is closer to a source gate than a test
// is: not a check that catches an off-vocabulary class, a build that cannot
// express one.
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokensPath = join(here, '..', 'src', 'generated', 'design-tokens.json');
const outPath = join(here, '..', 'src', 'app', 'theme.generated.css');

const tokens = JSON.parse(readFileSync(tokensPath, 'utf8'));

/** lowerCamel to kebab, so `surfaceRaised` is `--color-surface-raised`. */
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const lines = [];
const w = (line = '') => lines.push(line);

w('/* Generated by scripts/gen-theme.mjs from src/generated/design-tokens.json.');
w('   Do not edit. The values are dew::tokens, read out of darkPalette() by');
w('   `dew_shot tokens` - so this file cannot disagree with the application. */');
w();
w('@theme {');
w('  /* Close the vocabulary. After these, bg-blue-500 emits nothing at all. */');
w('  --color-*: initial;');
w('  --spacing: initial;');
w('  --radius-*: initial;');
w('  --text-*: initial;');
w('  --font-*: initial;');
w();

for (const [name, value] of Object.entries(tokens.colour)) w(`  --color-${kebab(name)}: ${value};`);

w();
w('  /* A lift is juce::Colour::brighter, which is per sRGB channel and');
w('     TRUNCATES where CSS color-mix rounds. These are the bytes the app');
w('     paints, computed by that same call - never re-derived here.');
w();
w('     Note surface-raised-hover is NOT color-surface-hover. They are');
w('     different colours doing different jobs, and the one whose name says');
w('     "hover" is the darker of the two. */');

for (const [name, value] of Object.entries(tokens.lift)) w(`  --color-${kebab(name)}: ${value};`);

w();
w('  /* Document data, written into every .dew file. Not themeable. */');
tokens.channelRamp.forEach((value, i) => w(`  --color-channel-${i}: ${value};`));

w();
w('  /* px/16, so browser zoom carries the layout. A deliberate divergence:');
w('     in the app a rung is a device pixel at scale 1. */');
for (const [name, value] of Object.entries(tokens.space))
  w(`  --spacing-${name}: ${value / 16}rem;`);

w();
w('  /* px, not rem: a 3px radius must stay 3px at any zoom. */');
for (const [name, value] of Object.entries(tokens.radius)) w(`  --radius-${name}: ${value}px;`);

w();
for (const [name, value] of Object.entries(tokens.type))
  w(`  --text-${kebab(name)}: ${value / 16}rem;`);

w();
w('  /* dew bundles no typeface and neither does this: tokens::type::font asks');
w('     for the system face, and type::monospaced for the system monospace. */');
w('  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;');
w('  --font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;');
w('}');
w();
w('/* Namespaces Tailwind has no @theme key for. Each gets a custom property and');
w('   one @utility below, so no dimension is ever written as an arbitrary value. */');
w(':root {');

for (const [name, value] of Object.entries(tokens.stroke)) w(`  --stroke-${name}: ${value}px;`);
w();

// Percentages, not floats. Tailwind's opacity modifier takes a percentage, and
// a stray 0.55 in that position silently means 0.55% - invisible in review and
// invisible on the page.
for (const [name, value] of Object.entries(tokens.emphasis))
  w(`  --emphasis-${kebab(name)}: ${Math.round(value * 100)}%;`);

w();
for (const [name, value] of Object.entries(tokens.motion))
  w(`  --motion-${kebab(name)}: ${name.endsWith('Px') ? `${value}px` : `${value}ms`};`);

w('}');
w();

for (const name of Object.keys(tokens.stroke))
  w(`@utility border-${name} {\n  border-width: var(--stroke-${name});\n}`);

// `text-text-primary` reads badly, and these four are written on nearly every
// element. Shorthands for the text roles only - not a general escape hatch.
for (const role of ['primary', 'secondary', 'disabled', 'on-accent'])
  w(`@utility text-${role} {\n  color: var(--color-text-${role});\n}`);

const css = lines.join('\n') + '\n';

if (process.argv.includes('--check')) {
  const existing = readFileSync(outPath, 'utf8');

  if (existing !== css) {
    console.error('theme.generated.css is stale. Run: npm run theme');
    process.exit(1);
  }

  console.log('ok    theme.generated.css matches design-tokens.json');
} else {
  writeFileSync(outPath, css);
  console.log(`wrote ${outPath}`);
}
