// =============================================================================
// src/generated/design-tokens.json -> src/app/theme.generated.css
//
//     node scripts/gen-theme.mjs           write it
//     node scripts/gen-theme.mjs --check   fail if what is committed is stale
//
// Tailwind v4 rather than v3, and this file is the reason. In v4 `@theme`
// both defines the custom property on :root AND generates the utilities, so
// one declaration is one home. A v3 tailwind.config.js would hold the palette
// and anything needing the raw value - a gradient stop, a color-mix - would
// need a second :root block kept in step by hand. That is the second
// vocabulary src/ui/design/Tokens.h exists to end, rebuilt in CSS.
//
// The namespace resets are load-bearing. `--color-*: initial` deletes
// Tailwind's own palette, so `bg-blue-500` and `bg-slate-800` do not exist and
// emit nothing; `--spacing: initial` deletes the dynamic p-3/p-7 scale, leaving
// only the seven rungs dew names. That is closer to a source gate than a test
// is: not a check that catches an off-vocabulary class, a build that cannot
// express one.
// =============================================================================
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokensPath = join(here, '..', 'src', 'generated', 'design-tokens.json');
const outPath = join(here, '..', 'src', 'app', 'theme.generated.css');
const iconPath = join(here, '..', 'src', 'app', 'icon.svg');
// Outside website/, and the one output that is. The application needs the same
// mark - a Linux .desktop entry and an AppImage both want an icon file - and a
// second SVG drawn by hand would be a second home for it, drifting the first
// time the accent moves. So the generator writes both copies and --check holds
// both, which is the arrangement every other generated file here already has.
const appIconPath = join(here, '..', '..', 'resources', 'icon', 'dew.svg');

const tokens = JSON.parse(readFileSync(tokensPath, 'utf8'));

/** lowerCamel to kebab, so `surfaceRaised` is `--color-surface-raised`. */
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const lines = [];
const w = (line = '') => lines.push(line);

w('/* Generated by scripts/gen-theme.mjs from src/generated/design-tokens.json.');
w('   Do not edit. The values are dew::tokens, read out of darkPalette() by');
w('   `dew_shot tokens` - so this file cannot disagree with the application. */');
w();
w('@theme {');
w('  /* Close the vocabulary. After these, bg-blue-500 emits nothing at all. */');
w('  --color-*: initial;');
w('  --spacing: initial;');
w('  --radius-*: initial;');
w('  --text-*: initial;');
w('  --font-*: initial;');
w();

for (const [name, value] of Object.entries(tokens.colour)) w(`  --color-${kebab(name)}: ${value};`);

w();
w('  /* A lift is juce::Colour::brighter, which is per sRGB channel and');
w('     TRUNCATES where CSS color-mix rounds. These are the bytes the app');
w('     paints, computed by that same call - never re-derived here.');
w();
w('     Note surface-raised-hover is NOT color-surface-hover. They are');
w('     different colours doing different jobs, and the one whose name says');
w('     "hover" is the darker of the two. */');

for (const [name, value] of Object.entries(tokens.lift)) w(`  --color-${kebab(name)}: ${value};`);

w();
w('  /* Document data, written into every .dew file. Not themeable. */');
tokens.channelRamp.forEach((value, i) => w(`  --color-channel-${i}: ${value};`));

w();
w('  /* px/16, so browser zoom carries the layout. A deliberate divergence:');
w('     in the app a rung is a device pixel at scale 1. */');
for (const [name, value] of Object.entries(tokens.space))
  w(`  --spacing-${name}: ${value / 16}rem;`);

w();
w('  /* px, not rem: a 3px radius must stay 3px at any zoom. */');
for (const [name, value] of Object.entries(tokens.radius)) w(`  --radius-${name}: ${value}px;`);

w();
for (const [name, value] of Object.entries(tokens.type))
  w(`  --text-${kebab(name)}: ${value / 16}rem;`);

w();
w('  /* dew bundles no typeface and neither does this: tokens::type::font asks');
w('     for the system face, and type::monospaced for the system monospace. */');
w('  --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;');
w('  --font-mono: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;');
w('}');
w();
w('/* Namespaces Tailwind has no @theme key for. Each gets a custom property and');
w('   one @utility below, so no dimension is ever written as an arbitrary value. */');
w(':root {');

for (const [name, value] of Object.entries(tokens.stroke)) w(`  --stroke-${name}: ${value}px;`);
w();

// Percentages, not floats. Tailwind's opacity modifier takes a percentage, and
// a stray 0.55 in that position silently means 0.55% - invisible in review and
// invisible on the page.
for (const [name, value] of Object.entries(tokens.emphasis))
  w(`  --emphasis-${kebab(name)}: ${Math.round(value * 100)}%;`);

w();
for (const [name, value] of Object.entries(tokens.motion))
  w(`  --motion-${kebab(name)}: ${name.endsWith('Px') ? `${value}px` : `${value}ms`};`);

w('}');
w();

// Each stroke rung, and each SIDE of it.
//
// `@utility border-hairline` defines exactly one class. Tailwind does not
// derive `border-b-hairline` from it the way it derives border-b-2 from
// border-2 - a custom utility has no directional family - so every
// `border-t-hairline` and `border-b-hairline` on this site emitted nothing at
// all, and the nav's rule, the footer's rule and every row separator in the
// reference tables were absent rather than subtle. Nothing could catch it:
// the class was in the markup, the token was in the file, and only the
// compiled stylesheet knew. `tests/utilities.test.ts` reads that stylesheet
// now.
const sides = [
  ['', 'border-width'],
  ['t-', 'border-top-width'],
  ['r-', 'border-right-width'],
  ['b-', 'border-bottom-width'],
  ['l-', 'border-left-width'],
  ['x-', 'border-inline-width'],
  ['y-', 'border-block-width'],
];

for (const name of Object.keys(tokens.stroke))
  for (const [prefix, property] of sides)
    w(`@utility border-${prefix}${name} {\n  ${property}: var(--stroke-${name});\n}`);

// `text-text-primary` reads badly, and these four are written on nearly every
// element. Shorthands for the text roles only - not a general escape hatch.
for (const role of ['primary', 'secondary', 'disabled', 'on-accent'])
  w(`@utility text-${role} {\n  color: var(--color-text-${role});\n}`);

const css = lines.join('\n') + '\n';

// The favicon, from the same two colours.
//
// Generated rather than drawn, for the reason every colour on this site is:
// a hex value typed into an SVG is a copy of the palette that no gate can see,
// because the gates read .ts, .tsx and .css and a browser loading a favicon
// cannot reach a CSS custom property anyway. So it comes from the tokens here,
// where the tokens already are.
//
// A drop, which is what the name is: the accent, on the app's own window
// colour, at the radius a panel takes.
const icon = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32">
  <!-- Generated by scripts/gen-theme.mjs. Do not edit. -->
  <rect width="32" height="32" rx="7" fill="${tokens.colour.background}"/>
  <path d="M16 5c5 6.2 7.5 10.2 7.5 13.4A7.5 7.5 0 0 1 8.5 18.4C8.5 15.2 11 11.2 16 5Z"
        fill="${tokens.colour.accent}"/>
</svg>
`;

const stale = [
  [outPath, css, 'theme.generated.css'],
  [iconPath, icon, 'icon.svg'],
  [appIconPath, icon, '../resources/icon/dew.svg'],
];

if (process.argv.includes('--check')) {
  for (const [path, wanted, name] of stale) {
    if (readFileSync(path, 'utf8') !== wanted) {
      console.error(`${name} is stale. Run: npm run theme`);
      process.exit(1);
    }

    console.log(`ok    ${name} matches design-tokens.json`);
  }
} else {
  for (const [path, wanted] of stale) {
    writeFileSync(path, wanted);
    console.log(`wrote ${path}`);
  }
}
