#!/usr/bin/env bash
# ==============================================================================
# The website's screenshots, from the release build.
#
#     ./scripts/gen-shots.sh
#
# Six PNGs into website/public/shots, committed. They are regenerated
# DELIBERATELY, by running this. NOTHING CHECKS THAT THEY ARE CURRENT, and that
# is a decision rather than an omission: dew paints with the system typeface
# (tokens::type::font asks for it by height alone), so the pixels are a function
# of the macOS version and the installed fonts. A byte comparison would fail on
# somebody else's laptop for a reason with nothing to do with dew - which is the
# same thing THIRD_PARTY.md's missing generation date refuses to do.
#
# What IS checked is in tests/WebsiteShotTests.cpp: every shot decodes, is the
# size it was asked for, and is not one flat colour. And a shot the site
# references but does not have is a `next build` failure, because the pages
# import them by path.
#
# The RELEASE build, not build/ci: `build/ci` is not the app (see
# .ai/rules/workflow.md), and a picture of dew should come from the binary a
# user opens.
#
# Every project named below is committed under examples/, is itself generated by
# `dew_render --write-demos examples`, and is pinned byte for byte by a test. So
# the CONTENT of a shot is fixed and only the drawing of it can move.
# ==============================================================================
set -euo pipefail

cd "$(dirname "$0")/.."

SHOT=build/release/tools/dew_shot_artefacts/RelWithDebInfo/dew_shot
OUT=website/public/shots
SIZE=1440x900
SCALE=2

if [[ ! -x $SHOT ]]; then
  echo "FAIL  $SHOT is missing"
  echo "      run: cmake --build --preset release"
  exit 1
fi

mkdir -p "$OUT"

# --theme dark is stated rather than left to the default. The site is dark only,
# and a default is a thing that changes.
shoot() {
  local name=$1 project=$2 tab=$3

  "$SHOT" editor "$OUT/$name.png" \
    --project "examples/$project" --tab "$tab" \
    --size "$SIZE" --scale "$SCALE" --theme dark
}

# Each project is chosen for what that tab has to SHOW, not for variety.
shoot channel-rack demo.dew        channel-rack   # steps already programmed
shoot piano-roll   melody.dew      piano-roll     # notes worth looking at in a roll
shoot playlist     arrangement.dew playlist       # the only demo with clips across lanes
shoot mixer        effects.dew     mixer          # the only one whose strips hold inserts

# amber.dew and no other: dew_score stores the source it compiled INSIDE the
# project, so this is the one demo whose score tab has text in it.
shoot score        amber.dew       score

# The gallery takes a width and finds its own height - it is as tall as its
# sections need.
"$SHOT" gallery "$OUT/gallery.png" --size "$SIZE" --scale "$SCALE" --theme dark

# The application icon, from the SVG gen-theme.mjs writes out of the palette.
# It goes to resources/ rather than $OUT: it is not a screenshot, it is what
# ICON_BIG points at, and tests/IconTests.cpp holds it against that SVG.
"$SHOT" icon resources/icon/dew.png resources/icon/dew.svg

echo
echo "ok    $(find "$OUT" -name '*.png' | wc -l | tr -d ' ') shots in $OUT"
echo "      look at them before committing - nothing downstream will"
