# ==============================================================================
# Generates THIRD_PARTY.md from the dependency set that was actually resolved,
# so the manifest cannot drift from cpm-package-lock.cmake.
#
# It records the toolchain too: pinning libraries while the compiler floats is
# only half a reproducible build.
# ==============================================================================

define_property(GLOBAL PROPERTY DEW_THIRD_PARTY_ENTRIES
  BRIEF_DOCS "Resolved third-party packages" FULL_DOCS "Resolved third-party packages")

# dew_record_third_party(<name> <version> <sha> <url> <licence> <source_dir>)
function(dew_record_third_party name version sha url licence source_dir)
  set(licence_file "")
  foreach(candidate LICENSE.md LICENSE LICENSE.txt LICENCE.md COPYING)
    if(EXISTS "${source_dir}/${candidate}")
      set(licence_file "${candidate}")
      break()
    endif()
  endforeach()

  set_property(GLOBAL APPEND PROPERTY DEW_THIRD_PARTY_ENTRIES
    "${name}|${version}|${sha}|${url}|${licence}|${licence_file}")
endfunction()

# dew_write_third_party_manifest(<output_file>)
function(dew_write_third_party_manifest output)
  get_property(entries GLOBAL PROPERTY DEW_THIRD_PARTY_ENTRIES)

  # No generation date. CI regenerates this file and then diffs it against the
  # committed copy, so a date stamp makes the check fail on the first day after
  # the file was last committed - for the passage of time rather than for any
  # drift in the dependencies it exists to catch. What identifies a version here
  # is the commit SHA, which is in the table.
  set(body "# Third-party dependencies\n\n")
  string(APPEND body
    "Generated by CMake at configure time from the packages actually resolved --\n"
    "do not edit by hand. Regenerate with `cmake --preset release`.\n\n"
    "Source of truth: [cpm-package-lock.cmake](cpm-package-lock.cmake) (versions)\n"
    "and [cmake/DependencyPins.cmake](cmake/DependencyPins.cmake) (commit SHAs).\n\n"
    "## Libraries\n\n"
    "| Package | Version | Commit | Licence | Licence file | Source |\n"
    "|---|---|---|---|---|---|\n")

  foreach(entry IN LISTS entries)
    string(REPLACE "|" ";" fields "${entry}")
    list(GET fields 0 e_name)
    list(GET fields 1 e_version)
    list(GET fields 2 e_sha)
    list(GET fields 3 e_url)
    list(GET fields 4 e_licence)
    list(GET fields 5 e_licence_file)
    string(SUBSTRING "${e_sha}" 0 12 e_short)
    string(APPEND body
      "| ${e_name} | `${e_version}` | `${e_short}` | ${e_licence} | `${e_licence_file}` | [${e_url}](${e_url}) |\n")
  endforeach()

  string(APPEND body
    "\n## Build toolchain\n\n"
    "Recorded from the configure that generated this file. The Brewfile fixes the\n"
    "tool *set*; these are the versions that were actually used.\n\n"
    "| Tool | Version |\n"
    "|---|---|\n"
    "| CMake | `${CMAKE_VERSION}` |\n"
    "| Generator | `${CMAKE_GENERATOR}` |\n"
    "| C++ compiler | `${CMAKE_CXX_COMPILER_ID} ${CMAKE_CXX_COMPILER_VERSION}` |\n"
    "| C++ standard | `C++${CMAKE_CXX_STANDARD}` |\n"
    "| Target | `${CMAKE_SYSTEM_NAME} ${CMAKE_SYSTEM_PROCESSOR}` |\n")

  if(DEW_CCACHE_PROGRAM)
    string(APPEND body "| ccache | `${DEW_CCACHE_VERSION}` |\n")
  else()
    string(APPEND body "| ccache | not found (builds are slower, not incorrect) |\n")
  endif()

  file(WRITE "${output}" "${body}")
  message(STATUS "dew: wrote ${output}")
endfunction()
